
default:
	./pub tex index.tex
	(xelatex --interaction nonstopmode ladder.to.akanishta.tex; mv -f -v ladder.to.akanishta.pdf index.pdf)

pdf:
	(xelatex ladder.to.akanishta.tex; mv -f -v ladder.to.akanishta.pdf index.pdf)
