default:
	./pub tex index.tex
	(xelatex --interaction nonstopmode nendro.tex; mv -f -v nendro.pdf ../sngon.\'gro.pdf)

clean:
	rm -f *.aux
	rm -f *.toc
	rm -f *.haux
	rm -f *.htoc
	rm -f *.log
	rm -f temp.*

